### PR TITLE
Show date in title frame

### LINKED ISSUE #76: [BUG] `\date` not visible in `\titlepage{}`
When `\date{\today}` or similar is set and then `\titlepage` is called, the date does not appear.

This is also present on the demos in this repository:

image

### PR DESCRIPTION
**Pull request by earnestma**
* Closes #76
* As mentioned, subtitle is on a new line. I think i've done it correctly.
* To hide date, setting `\date{}` seems to work

### CODE REVIEW

**Comment by earnestma** [comment]
image

**Comment by kai-tub** [comment]
Hey, thank you for opening a PR!
I would prefer to change the order (to have the subtitle directly under the title).
Or do you have a specific reason to keep the order as is?

**Comment by earnestma** [comment]
I see what you mean! I've pushed that [change](https://github.com/kai-tub/latex-beamer-pure-minimalistic/compare/e4d23eb86ccedb5e5d6eae90b3e9e3f0c2d99eb1..1a1728ef69abddc2027bea8a261b1bedea00d662)

<details>
<summary>Image</summary>

image


</details>

**Comment by kai-tub** [comment]
LGTM.

The CI seems currently broken, which is not too surprising as it wasn't used in quite some time...
I will merge your code without releasing a new version for now.
Once I have the CI pipeline working again, I will double-check the different 'visual' tests and fix them on my own if necessary.
I might also change the vertical spacing between the elements, depending on what the output looks like for multi-row and single-row titles (just as an FYI).

Thank you for opening an issue and writing a PR!

**Pull request merged**
